stages:
  - build
  - test
  - deploy

test-job-ubuntu 1/2:
  stage: test
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Запуск unit тестов ubuntu"
  script:
    - python3 -m unittest main_test.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "dev"'
      when: on_success
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true

test-job-centos 2/2:
  stage: test
  image: kirillkom/lab_4_mfti:centos_img
  before_script:
    - echo "Запуск unit тестов на CentOS"
  script:
    - python3 -m unittest main_test.py
  allow_failure: true

#deploy-job-ubuntu-1/2:
#  stage: deploy
#  image: kirillkom/ubuntu_img:latest
#  before_script:
#    - echo "Деплой приложения на ОС Ubuntu"
#  script:
#    - ls -al
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME == "main"
#      when: manual

