stages:
  - build
  - test
  - post

test-job-ubuntu 1/2:
  stage: test
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Запуск unit тестов ubuntu"
  script:
    - python3 -m unittest main_test.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "dev"'
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
      allow_failure: true

test-job-centos 2/2:
  stage: test
  image: kirillkom/lab_4_mfti:centos_img
  before_script:
    - echo "Запуск unit тестов на CentOS"
  script:
    - python3 -m unittest main_test.py
  allow_failure: true

build-deb-job-ubuntu-1/2:
  stage: post
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Сборка deb пакета приложения для ОС Ubuntu"
  script:
    - pip install -y PyInstaller
    - pyinstaller main.py
    - apt install -y ruby
    - gem install fpm --user-install
    - fpm -C main -s dir -t deb -n "Translator" -v 0.0.1 -p translator.deb
  artifacts:
    paths:
      - translator.deb

