stages:
  - test
  - deploy

build-job-ubuntu:
  stage: test
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Запуск unit тестов ubuntu"
  script:
    - python3 -m unittest main_test.py
  artifacts:
    paths:
      - "app/"

build-job-centos:
  stage: test
  image: kirillkom/lab_4_mfti:centos_img
  before_script:
    - echo "Запуск unit тестов ubuntu"
  script:
    - python3 -m unittest main_test.py
  artifacts:
    paths:
      - "app/"

deploy-job-ubuntu:
  stage: deploy
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Деплой приложения на ОС Ubuntu"
  script:
    - ls -al
rules:
  - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "dev"' # Если источник пайплайна - push в ветку "dev"
    changes:
      - '**/*'
    when: always
    pipeline: test

  - if: '$CI_PIPELINE_SOURCE == "merge_request" && $CI_COMMIT_REF_NAME == "staging"' # Если источник пайплайна - merge request в ветку "staging"
    changes:
      - '**/*'
    when: always
    pipeline:
      - test
      - deploy

  - if: '$CI_PIPELINE_SOURCE == "merge_request" && $CI_COMMIT_REF_NAME == "main"' # Если источник пайплайна - merge request в ветку "main"
    changes:
      - '**/*'
    when: always
    pipeline:
      - test
      - deploy
