stages:
  - test
  - deploy

build-job-ubuntu:
  stage: test
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Запуск unit тестов ubuntu"
  script:
    - python3 -m unittest main_test.py
  artifacts:
    paths:
      - "app/"

build-job-centos:
  stage: test
  image: kirillkom/lab_4_mfti:centos_img
  before_script:
    - echo "Запуск unit тестов ubuntu"
  script:
    - python3 -m unittest main_test.py
  artifacts:
    paths:
      - "app/"

deploy-job-ubuntu:
  stage: deploy
  image: kirillkom/ubuntu_img:latest
  before_script:
    - echo "Деплой приложения на ОС Ubuntu"
  script:
    - ls -al

# При push в ветку dev запускается частичный пайплайн (только test задания)
test_pipeline:
  stage: test
  script:
    - echo "Запуск частичного пайплайна (только test)"
    - echo "Выполнение тестов для dev"
  rules:
    - exists:
        - $CI_COMMIT_REF_NAME
    - changes:
        - app/**/*  # Выполнить пайплайн только если были изменения в папке "app"

# При Merge Request из dev в staging запускается полный пайплайн (test + deploy задания)
staging_pipeline:
  stage: test
  script:
    - echo "Запуск полного пайплайна (test + deploy)"
    - echo "Выполнение тестов для staging"
  rules:
    - exists:
        - $CI_COMMIT_REF_NAME
    - changes:
        - app/**/*  # Выполнить пайплайн только если были изменения в папке "app"
    - exists:
        - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - changes:
        - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:**/*
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:**/*

# При Merge Request из staging в main запускается полный пайплайн (test + deploy задания)
main_pipeline:
  stage: test
  script:
    - echo "Запуск полного пайплайна (test + deploy)"
    - echo "Выполнение тестов для main"
  rules:
    - exists:
        - $CI_COMMIT_REF_NAME
    - changes:
        - app/**/*  # Выполнить пайплайн только если были изменения в папке "app"
    - exists:
        - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - changes:
        - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:**/*
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME:**/*