# Используйте базовый образ CentOS
FROM centos:latest

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum update -y && \
    yum clean all

# Установите зависимости системы
RUN yum -y update
RUN yum install -y \
    python3 \
    python3-pip \
    libX11 \
    libX11-devel \
    libXext \
    libXrender \
    libXrandr \
    libXcursor \
    libxcb \
    libXinerama \
    mesa-libGL \
    gtk2 \
    gtk2-devel \
    xcb-util \
    xcb-util-*

RUN yum install -y mesa-libEGL
RUN ln -s /usr/lib64/libEGL.so.1 /usr/lib64/libEGL.so

ENV QT_QPA_PLATFORM offscreen
# Обновите pip
RUN pip3 install --upgrade pip

# Установите зависимости проекта
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

# Скопируйте все файлы проекта в образ
COPY main.py task_1.py main_test.py /app/

# Установите рабочую директорию внутри контейнера
WORKDIR /app

# Запустите приложение
CMD python3 main.py