# Используйте базовый образ Ubuntu
FROM ubuntu:latest

# Установите зависимости системы
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libgl1-mesa-glx \
    libxkbcommon-x11-0 \
    libegl1 \
    libgtk2.0-dev \
    libxcb-xinerama0 \
    libxcb-shape0 \
    libxcb1 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-image0 \
    libxcb-shm0 \
    libxcb-sync1 \
    libxcb-xfixes0 \
    libxcb-render0 \
    libxcb-xtest0 \
    libxcb-cursor0 \
    libxcb-cursor-dev \
    libxcb-*

ENV QT_QPA_PLATFORM offscreen


RUN pip3 install --upgrade pip

# Установите зависимости проекта
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

# Скопируйте все файлы проекта в образ
COPY main.py task_1.py main_test.py /app/

# Установите рабочую директорию внутри контейнера
WORKDIR /app

# Запустите приложение
CMD python3 main.py