# Используйте базовый образ CentOS
FROM centos:latest

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum update -y && \
    yum clean all

# Установите зависимости системы
RUN yum -y update
RUN yum -y install python3 python3-pip
# Обновите pip
RUN pip3 install --upgrade pip

# Установите зависимости проекта
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

# Скопируйте все файлы проекта в образ
COPY main.py task_1.py main_test.py /app/

# Установите рабочую директорию внутри контейнера
WORKDIR /app

# Запустите приложение
CMD python3 main.py