---
- hosts: all
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - dpkg
        - curl

    - name: Download deb package

